name: Greetings

on: [pull_request_target, issues]

jobs:
  greeting: Sup
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
    - uses: actions/first-interaction@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        issue-message: "Ooops,what did you do?"
        pr-message: "Sup, let me see what you did there"
